#!/bin/bash
#
# Documentation of tools/print_config.py
# https://mmdetection.readthedocs.io/en/v2.18.1/tutorials/config.html

export CUDA_VISIBLE_DEVICES=-1
python /mmdetection/tools/misc/print_config.py "$@"
